---
title: "using tidymodels to model vaccination rate data"
author: "chad allison"
date: '2023-02-03'
output: github_document
---

### setup

```{r message = F, warning = F}
tictoc::tic()
library(tidyverse)
library(tidymodels)

theme_custom = tvthemes::theme_avatar() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.major = element_line(linewidth = 0.5, colour = "#D6D0C4"),
        panel.grid.minor = element_line(linewidth = 0.5, colour = "#D6D0C4"))

theme_set(theme_custom)
```

___

### data import

```{r}
link = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-25/measles.csv"
measles = read_csv(link, col_types = cols())
glimpse(measles)
```

___

### creating data frame tracking if schools are above or below threshold

```{r}
measles_df = measles |>
  filter(mmr > 0) |>
  transmute(state,
            mmr_threshold = case_when(mmr > 95 ~ "above",
                                      T ~ "below")) |>
  mutate_if(is.character, factor)

sample_n(measles_df, 10)
```

___

### average rate of vaccination by state

```{r}
measles_df |>
  group_by(state) |>
  summarise(mmr = round(mean(mmr_threshold == "above"), 3)) |>
  arrange(desc(mmr)) |>
  ggplot(aes(reorder(state, mmr), mmr)) +
  geom_col(fill = "#A390AD", position = "dodge") +
  geom_text(aes(label = mmr), hjust = -0.25, size = 3) +
  coord_flip(ylim = c(0, 0.95)) +
  labs(x = "state", y = "above threshold rate",
       title = "average vaccination rate by state")
```

___

### above/below threshold counts by state

```{r}
measles_df |>
  count(state, mmr_threshold) |>
  ggplot(aes(reorder(state, n), n)) +
  geom_col(aes(fill = mmr_threshold), position = "dodge") +
  coord_flip() +
  scale_fill_manual(values = c("#A5BDA3", "#D89E9E")) +
  labs(x = "state", y = "count", fill = "above/below threshold",
       title = "counts of schools above/below threshold by state") +
  theme(legend.position = "right")
```

___

### continue here

```{r}
glimpse(measles_df)
```

___













### script runtime

```{r}
tictoc::toc()
```






















































